name: LinkGrabber

on:
  schedule:
    - cron: '0 */3 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grab Link

                run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add youtube.m3u8
          git commit -m "Update youtube.m3u8 links" || echo "No changes to commit"
          git push
